### ISSUE TITLE
Plugin crashes when used alongside logstash-input-google_pubsub

### ISSUE THREAD

**Issue by fkoclas** [logstash-plugins/logstash-output-google_pubsub#7]
Hi,

I'm trying to replace kafka with pub/sub in our logging stack. Right now I am unable to read from pub/sub in a pipeline that also outputs to pub/sub.

Whenever I input from another source, i.e. `stdin` or `kafka`, it works. But as soon as I use the` logstash-input-google_pubsub` (1.2.0) alongside the `logstash-output-google_pubsub` (v1.0.0), Logstash crashes.

I am currently testing it in the official Logstash 5.6.10 docker image.

Working config using `stdin` as input:
```
input {
  stdin {
    id => "stdin-input"
  }
}

output {
  google_pubsub {
    id => "pubsub-output"
    project_id => "project_name"
    topic => "output_topic"
    json_key_file => "/path/to/service_account.json"
  }
}
```

Config that crashes:
```
input {
  google_pubsub {
    id => "pubsub-input"
    project_id => "project_name"
    topic => "input_topic"
    subscription => "logstash_processor"
    json_key_file => "/path/to/service_account.json"
  }
}

output {
  google_pubsub {
    id => "pubsub-output"
    project_id => "project_name"
    topic => "output_topic"
    json_key_file => "/path/to/service_account.json"
  }
}
```

Here is the stack trace:
```
[2018-07-30T18:04:53,695][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<TypeError: cannot convert instance of class org.jruby.RubyString to class com.google.pubsub.v1.TopicName>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-google_pubsub-1.0.0-java/lib/logstash/outputs/pubsub/client.rb:64:in `initialize_google_client'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-google_pubsub-1.0.0-java/lib/logstash/outputs/pubsub/client.rb:14:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-google_pubsub-1.0.0-java/lib/logstash/outputs/google_pubsub.rb:48:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:43:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:290:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:310:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:235:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:408:in `start_pipeline'"]}
```

**Comment by josephlewis42** [comment]
I think I might see what's going on here, there's a version mismatch between the Pub/Sub client library imported by [this plugin](https://github.com/logstash-plugins/logstash-output-google_pubsub/blob/master/lib/logstash-output-google_pubsub_jars.rb) and the Pub/Sub [input plugin](https://github.com/logstash-plugins/logstash-input-google_pubsub/blob/master/lib/logstash-input-google_pubsub_jars.rb).

Logstash doesn't _yet_ support classloading isolation but it's on the roadmap: https://github.com/elastic/logstash/issues/9521. So the solution might be to bump up the dependency on that plugin to match this one.

@fkoclas would you be willing to try your setup with a custom gemfile with the fix if I could send it to you?

**Comment by fkoclas** [comment]
Sure thing. I was building the gem myself last week when testing, I can always test a newer version.

**Comment by josephlewis42** [comment]
Hi @fkoclas 

I've bumped up the JARs used in `logstash-input-google_pubsub` and fixed a few incompatibilities that popped up with that so it uses the same version used in this plugin and released [a gem in my own fork](https://github.com/josephlewis42/logstash-input-google_pubsub/releases/tag/v1.2.1-alpha) you can try out.

You'll need to use Logstash 6.3.2 because 6.3.1 and the 6.2.x branches accidentally reverted their version of guava to one that's too early for this plugin but the 6.3.2 version has one that's good enough.

I tried it out with messages published with gcloud but not in conjunction with this plugin.

If that works for you I'll do a PR on that plugin and cc you over there as a community member that tested it out and we can get it merged in officially.

Thanks!
- Joseph

**Comment by josephlewis42** [comment]
Hi @fkoclas, were you able to test this out with your setup?

**Comment by fkoclas** [comment]
Hi @josephlewis42, sorry for the delay, I was caught up in other things.

Your 1.2.1 pubsub input gem seems to work fine alongside this output plugin :+1:

**Comment by praveenuchiha** [comment]
Any update on when the new release might be? (with the fix merged)

**Comment by josephlewis42** [comment]
The gem has been published and you should be able to upgrade to it now: https://rubygems.org/gems/logstash-input-google_pubsub/versions/1.2.1

I'm going to close this issue out and we can re-open if necessary.
